artifact_location: /Users/mtounekti/projects/telemed-urgence-ia/notebooks/../mlflow/797759043154675385
creation_time: 1780149767272
experiment_id: '797759043154675385'
last_update_time: 1780149767272
lifecycle_stage: active
name: telemed-urgence-ia
trace_location: null
workspace: default
