version: "3.9"

services:

  api:
    build: .
    container_name: telemed-api
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./src/models:/app/src/models
    restart: unless-stopped

  ui:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: telemed-ui
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000
    restart: unless-stopped