artifact_uri: /Users/mtounekti/projects/telemed-urgence-ia/notebooks/../mlflow/797759043154675385/6d1c7e226e4c49688d419875a3fcba56/artifacts
end_time: 1780149767707
entry_point_name: ''
experiment_id: '797759043154675385'
lifecycle_stage: active
run_id: 6d1c7e226e4c49688d419875a3fcba56
run_name: S4_tabulaire_seul__RandomForest
source_name: ''
source_type: 4
source_version: ''
start_time: 1780149767700
status: 3
tags: []
user_id: mtounekti
