artifact_uri: /Users/mtounekti/projects/telemed-urgence-ia/notebooks/../mlflow/797759043154675385/f4e5ba8dcb814e0b9e82b6e97aad1867/artifacts
end_time: 1780149767640
entry_point_name: ''
experiment_id: '797759043154675385'
lifecycle_stage: active
run_id: f4e5ba8dcb814e0b9e82b6e97aad1867
run_name: S2_sans_sensibles__MLP
source_name: ''
source_type: 4
source_version: ''
start_time: 1780149767628
status: 3
tags: []
user_id: mtounekti
