artifact_uri: /Users/mtounekti/projects/telemed-urgence-ia/notebooks/../mlflow/797759043154675385/9d6c0ca838714fcfbbee53d55e281472/artifacts
end_time: 1780149767667
entry_point_name: ''
experiment_id: '797759043154675385'
lifecycle_stage: active
run_id: 9d6c0ca838714fcfbbee53d55e281472
run_name: S3_nlp_seul__XGBoost
source_name: ''
source_type: 4
source_version: ''
start_time: 1780149767659
status: 3
tags: []
user_id: mtounekti
