artifact_uri: /Users/mtounekti/projects/telemed-urgence-ia/notebooks/../mlflow/797759043154675385/aad606c624bb48c2acdde2a685581479/artifacts
end_time: 1780150753398
entry_point_name: ''
experiment_id: '797759043154675385'
lifecycle_stage: active
run_id: aad606c624bb48c2acdde2a685581479
run_name: FINAL__LogReg_S1_best_model
source_name: ''
source_type: 4
source_version: ''
start_time: 1780150750156
status: 3
tags: []
user_id: mtounekti
