artifact_uri: /Users/mtounekti/projects/telemed-urgence-ia/notebooks/../mlflow/797759043154675385/c2adddf336a0478ab2d92268d1576daf/artifacts
end_time: 1780149767627
entry_point_name: ''
experiment_id: '797759043154675385'
lifecycle_stage: active
run_id: c2adddf336a0478ab2d92268d1576daf
run_name: S2_sans_sensibles__LightGBM
source_name: ''
source_type: 4
source_version: ''
start_time: 1780149767616
status: 3
tags: []
user_id: mtounekti
